//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerahomeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string Enable { get; set; }
        public string item_type { get; set; }
        public string meta_desc { get; set; }
        public string meta_key { get; set; }
    }
}
